displayName: Portfolio Analyst Miva
schemaName: crcc1_portfolioanalystmiva_DF7Nlm
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  recognizer:
    kind: CLICopilotRecognizer

  agentSettings:
    model:
      series: claude-opus-5

    instructions: {}
    web:
      enableWebSearch: true

template: cliagent-1.0.0
language: 1033